--- 
title: "Using GIS for invasive species research"
author: "Anthony Davidson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: davan690/Creating-maps-in-R
url: 'https://www.ssnhub.com/beech-publication-wr'
description: "Everything you need to start using GIS in RMarkdown/bookdown projects."
---

# Overview {#overview}

This respository contains a collection of dynamic programming tools and introductory tutorials for mapping/GIS from the following `github` repositories:

- [Creating maps in R](): A textbook on geocomputational analysis in R

- []():  and other supporting documents ranging from blogs to scientific publications coming below...

## The objectives

generally the objective is to create a landing page and resource of GIS work in R with a particular focus on invasive species dynamics. The current goals under my PhD work is as follows:

### One 

Produce static maps for the first publication of my PhD. [Draft here](https://www.ssnhub.com/2019-05-03-beech-forest-objectives).

- Datasets
  - Grid locations are in a csv file called ""
  - Outline of NZ here ""
  - Forest vegetation here ""
  - Data from landCare 2019 publication here ""

- Rcode
  - My attempt so far ""
  - GIS cheat ""
  - Powerpoint cheat ""

- Static maps
  - NZ beech forest dynamics
  - 8 grids full data
  - only 6 used
  - South Island of NZ

### Two

Produce static maps for the following data-set (Davidson2019b)

*same as above*

### Three

Produce static maps for the following data-set (Davidson2019c)

*same as above*

## Resources

- Vignettes
  - Creating maps in R ""
  - Book vignettes ""
  - My developing docs ""

- Examples
  - LandCare 2019 publication here ""
  
- Software
  - This is the absolute minimum you need to start a [bookdown](https://bookdown.org/yihui/bookdown/) book. You can find the
preview of this book at http://seankross.com/bookdown-start/
- All of the content of this repository is licensed [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

## My notes
