---
title: "REPRODUCIBLE EXAMPLE <br> April 2019"
always_allow_html: yes
output:
  html_document:
  self_contained: false
df_print: paged
---
  
# {.tabset .tabset-fade}
  
## TAB 1
  
### HEADING 1
  
```{r natl_map, echo = FALSE, message=FALSE, warning=FALSE, comment=NA, out.width='100%'}
library(leaflet)
library(leaflet.extras)
library(htmlwidgets)
library(dplyr)

make_map <- function() {
  leaflet() %>%
    addProviderTiles("OpenStreetMap.BlackAndWhite") %>%
    setView(lng = 30.2189853, lat = 7.1751893, zoom = 7) %>%
    setMaxBounds(
      lng1 = 22.625227,
      lat1 = 1.422041, 
      lng2 = 36.978083,
      lat2 = 13.528717 
    ) %>% 
    # addResetMapButton() %>%
    addEasyButton(
      easyButton(
        icon = "ion-arrow-shrink", 
        title = "Reset View", 
        onClick = JS(
          "function(btn, map){ map.setView(map._initialCenter, map._initialZoom); }"
        )
      )
    ) %>% 
    htmlwidgets::onRender(
      JS(
        "
function(el, x){ 
  var map = this; 
  map.whenReady(function(){
    map._initialCenter = map.getCenter(); 
    map._initialZoom = map.getZoom();
  });
}"
      )
    ) %>%
    force()
  
}
make_map()
```

## TAB 2

### HEADING 2

```{r cent_map, echo = FALSE, message=FALSE, warning=FALSE, comment=NA, out.width='100%'}
make_map()
```

## TAB 3

### HEADING 3

```{r east_map, echo = FALSE, message=FALSE, warning=FALSE, comment=NA, out.width='100%'}
make_map()
```

## TAB 4

### HEADING 4

```{r map4, echo = FALSE, message=FALSE, warning=FALSE, comment=NA, out.width='100%'}
make_map()
```